Module7 task1
htmlacademy-ecmascript/460147-big-trip-12 pull request #11
Opened 2020-09-16 19:31 UTC by alex1031alex

2020-09-17 20:51 UTC, likerRr commented on src/utils/event.js
> +  [FilterType.FUTURE]: (events) => events.filter((event) => event.date.start > new Date()),
Приучивайся никогда не сравнивать даты напрямую. Тут есть очень много нюансов, когда сравнение работать не будет. Самый точный способ сравнивать не сами объекты дат, а их числовое значение: `event.date.start.getTime() > new Date().getTime()`. Есть ещё один нюанс в сравнении, как ты спроектировал. Тут у тебя `new Date()` генерируется на каждой итерации, что, потенциально, при большом объёме массива может давать значения отличные от первоначального. То есть на первой итерации кол-во миллисекунд у `new Date()` будет меньше, чем на последней. В нашем проекте это не столь критично, но держи это в голове. Правильнее здесь было бы сделать так:

```js
(events) => {,
    const now = new Date();

    return events.filter((event) => event.date.start.getTime() > now.getTime())
}
```

2020-09-17 20:51 UTC, likerRr commented on src/presenter/trip.js
> +    if (this._sortingView !== null) {
Зачем этот if? Он не делает абсолютно ничего полезного)

2020-09-17 20:51 UTC, likerRr commented on src/presenter/event.js
> +    !isDatesEqual(this._event.date.start, updatedEvent.date.start) ||
Добавь отступ

2020-09-17 20:51 UTC, likerRr commented on src/view/event-form.js
> +    id="event-favorite-1"
Отступ

2020-09-17 20:51 UTC, likerRr commented on src/view/event-form.js
> +  if (!destination.name || destination.name === null) {
Достаточно отсавить одну проверку `if (!destination.name)`

2020-09-17 20:51 UTC, likerRr commented on src/view/event-form.js
> +    .getElement()
Отступ

2020-09-27 18:17 UTC, likerRr requested changes

2020-09-27 18:17 UTC, likerRr commented on src/main.js
> +  }
`newEventButton.disabled = isButtonDisabled`

2020-09-27 18:17 UTC, likerRr commented on src/presenter/trip.js
> +  addNewEvent(disableButton) {
Из названия аргумента непонятно, какая кнопка дизейблится

2020-09-27 18:17 UTC, likerRr commented on src/presenter/event-new.js
> +  init(disableButton) {
Из названия аргумента непонятно, какая кнопка дизейблится

2020-09-27 18:17 UTC, likerRr commented on src/presenter/event-new.js
> +    this._destinationsModel = destinationsModel;
Неиспользуемое свойство

2020-09-27 18:17 UTC, likerRr commented on src/mock/offers.js
> +const types = [...transferTypes, ...activityTypes];
Непонятное название переменной

2020-09-27 18:17 UTC, likerRr commented on src/mock/offers.js
> +
Лишняя пустая строка

2020-09-27 18:17 UTC, likerRr commented on src/mock/offers.js
> +      const updatedOffers = Array.from(new Set(draftOffers));
Я бы назвал это `uniqueOffers`

2020-09-27 18:17 UTC, likerRr commented on src/presenter/event.js
> +        {
Отступы

2020-09-27 18:17 UTC, likerRr commented on src/view/event-form.js
> +  const isChecked = offer.isChecked ? offer.isChecked : false;
`const isChecked = !!offer.isChecked`

2020-09-27 18:17 UTC, likerRr commented on src/view/event-form.js
> +        event,
Отступы

2020-09-27 18:17 UTC, likerRr commented on src/main.js
> +    eventsContainer,
Отступы

2020-09-27 18:17 UTC, likerRr commented on src/main.js
> +    offersModel);
Скобку перенеси на следующую строку

2020-09-27 18:17 UTC, likerRr commented on src/presenter/trip.js
> +        this._dayListView,
Отступы

2020-09-27 20:19 UTC, merged

2020-09-27 21:07 UTC, alex1031alex commented on src/presenter/event-new.js
> +        UserAction.ADD_EVENT,
Тут линтер требует именно двойной отступ. Я так понимаю, это при записи в столбик аргументов функции такая настройка.

2020-09-27 21:09 UTC, alex1031alex commented on src/main.js
> +  }
Совсем забыл что так можно)

2020-09-27 21:27 UTC, alex1031alex commented on src/presenter/event.js
> +        {
Тут та же ситуация: если аргументы в столбик, линтер требует двойной отступ.