Module5 task1
htmlacademy-ecmascript/460147-big-trip-12 pull request #7
Opened 2020-08-28 20:10 UTC by alex1031alex

2020-08-29 09:39 UTC, likerRr requested changes

2020-08-29 09:39 UTC, likerRr commented on src/presenter/trip.js
> +      if (evt.key === FULL_ESC_KEY || evt.key === SHORT_ESC_KEY) {
Создай функцию в `common.js`, которая по событию будет определять, что нажата кнопка эскейп, чтобы инкапсулировать логику в одном месте: `isEscKey(evt)`

2020-08-29 09:39 UTC, likerRr commented on src/presenter/trip.js
> +  init(events) {
Несмотря на то, что такое имя метода предлагает академия, лично мне кажется это немного обманчивым. Инициализация класса происходит в конструкторе, а в данном местоде мы реализуем рендер. Поэтому, логичнее было бы назвать метод `render`

2020-08-29 09:39 UTC, likerRr commented on src/presenter/trip.js
> +    .sort((a, b) => a.date.start - b.date.start)
Добавь отступ перед `sort` и `forEach`

2020-08-29 09:39 UTC, likerRr commented on src/presenter/trip.js
> +        const eventsList = this._eventsContainer.querySelector(`[data-day="${index + 1}"] .trip-events__list`);
Элемент с аттрибутом `data-day` находится в `DayView`, поэтому лучше добавь в него метод, который тебе будет по индексу возвращать нужный эллемент. Избегай использования `querySelector` за пределами компонентов

2020-08-29 09:39 UTC, likerRr commented on src/presenter/trip.js
> +    const dayList = this._eventsContainer.querySelector(`.trip-days`);
Эллемент с классом `trip-days` находится в компоненте `Days`, добавь в него метод для получения этого эллемента

2020-08-29 09:43 UTC, merged

2020-08-30 07:44 UTC, alex1031alex commented on src/presenter/trip.js
> +        const eventsList = this._eventsContainer.querySelector(`[data-day="${index + 1}"] .trip-events__list`);
Исправил. Мне кажется, тут даже индекс не нужен, так как на каждой итерации forEach у нас есть доступ только к одному инстансу класса DayView. Поэтому можно просто получать из него список, в который будут отрисованы эвенты. Возможно, что и сам атрибут data-day также не нужен.

2020-08-30 07:52 UTC, alex1031alex commented on src/presenter/trip.js
> +    const dayList = this._eventsContainer.querySelector(`.trip-days`);
Тут даже проще оказалось: элемент с классом trip-days это и есть разметка DaysView. Получаем её путём this._daysView.getElement();